### ISSUE TITLE
Halaman pengaturan

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#13]
## Scenario

- User dapat mengatur notifikasi bencana nyala/mati
- User dapat mengakses panduan penggunaan aplikasi dari halaman ini
- User dapat mengakses halaman tentang dari aplikasi ini

### Task

- [x] Simpan preferensi pengaturan notifikasi user dengan SharedPreferences
- [ ] Sediakan menu panduan
- [x] Sediakan menu tentang
