### ISSUE TITLE
Daftar Konten Edukasi Pra Bencana

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#2]
## Scenario

- User buka menu Edukasi Bencana
- Tampil daftar konten Edukasi Pra Bencana
- Ketika salah satu konten di klik, pindah ke halaman Detail

### Task
- [ ] Buat database konten dengan skema sqlite
- [ ] Akses database lokal dengan Room Database
- [ ] Setiap konten punya judul
- [ ] Setiap konten punya gambar thumbnail
- [ ] Setiap konten punya kategori
