### ISSUE TITLE
Halaman Detail Edukasi Pra Bencana

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#3]
## Scenario

- User membuka halaman detail dengan memilih salah satu konten dari daftar Edukasi Pra Bencana pada halaman sebelumnya #2 
- User seharusnya melihat beberapa panduan disertai dengan gambar
- User bisa melakukan _swipe_ untuk beralih menuju panduan berikutnya
- Ketika user sudah mencapai akhir dari panduan, seharusnya ada tombol yang dapat membuatnya kembali ke halaman daftar Edukasi Pra Bencana

### Task

- [ ] Mencari/membuat gambar-gambar yang sesuai dengan kategori bencana dan setiap aksi dari panduan
- [ ] Membuat halaman Detail yang nantinya digunakan User untuk mengakses panduan menghadapi bencana
- [ ] Menerapkan _swipe_ untuk berpindah panduan
- [ ] Ada tombol kembali ke halaman sebelumnya
