### ISSUE TITLE
Berita Bencana

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#4]
## Scenario

- User membuka menu Berita dari panel samping
- User melihat 5 berita terbaru dalam bentuk carousel (highlight berita yang bisa digeser")
- User melihat berita lainnya dalam bentuk grid dengan 2 kolom
- Ketika user memilih salah satu berita, maka akan terbuka jendela ChromeView yang menampilkan halaman website asli dari berita tersebut

### Task

- [x] Halaman berita sudah mempunyai carousel
- [x] Ketika berita diklik akan membuka jendela ChromeView yang menampilkan halaman website asli dari berita tersebut
- [x] Gunakan library Glide untuk menampilkan gambar

**Comment by affand20** [comment]
Fitur berita tinggal menampilkan data dari database aja
