### ISSUE TITLE
Notifikasi Bencana

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#5]
## Scenario

- Ketika web scrapper menemukan terjadi bencana sesuai yang ada di situs BMKG, maka web backend untuk push notif akan mengirim notifikasi ke seluruh user
- Notifikasi yang dikirim membawa data jenis bencana dan koordinat bencana
- Aplikasi di sisi User akan melakukan pengecekan jarak antara koordinat bencana dan posisi terkini User
- Apabila user dalam radius aman, aplikasi akan menampilkan notifikasi biasa seperti notifikasi pesan masuk
- Apabila user dalam radius bahaya, aplikasi akan menampilkan notifikasi yang berupa satu halaman penuh yang menunjukkan informasi bencana disertai dengan getaran perangkat
- Ketika user menekan tombol Cari Posko Evakuasi Terdekat dari halaman notifikasi yang muncul, maka user akan dibawa menuju halaman maps yang berisi beberapa letak posko evakuasi disertai dengan jalur menuju lokasi tersebut.

### Task

- [x] Aplikasi bisa menerima notifikasi biasa
- [x] Aplikasi bisa menerima notifikasi urgent berupa halaman yang menunjukkan informasi bencana
- [x] Web push notif
- [x] Tombol Cari Posko Evakuasi Terdekat sudah bekerja
- [x] Aplikasi sudah bisa handle notifikasi sesuai koordinat lokasi dan jenis bencana

**Comment by affand20** [comment]
Aplikasi sudah bisa menerima notifikasi yang urgent, tapi belum disertai dengan pengecekan koordinat terjadinya bencana

**Comment by affand20** [comment]
selesai dengan 8b670cd, karena fitur selesai, branch notifikasi dihapus
